name: Matrix Mapping Processing

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  process-mappings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mapping: [
          { "name": "mapping1", "value": "test1" },
          { "name": "mapping2", "value": "test2" },
          { "name": "mapping3", "value": "test3" }
        ]
    outputs:
      matrix-result: ${{ steps.set-matrix-result.outputs.result }}
    
    steps:
      - name: Process Mapping
        id: process
        run: |
          # Simulate processing of mapping
          result=$(jq -n \
            --arg name "${{ matrix.mapping.name }}" \
            --arg value "${{ matrix.mapping.value }}" \
            '{name: $name, processed_value: ($value + "_processed")}')
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Set Matrix Result
        id: set-matrix-result
        run: |
          echo "result=${{ steps.process.outputs.result }}" >> $GITHUB_OUTPUT

  merge-results:
    needs: process-mappings
    runs-on: ubuntu-latest
    steps:
      - name: Merge Results
        id: merge
        run: |
          # Collect all matrix job results and merge them
          results='${{ toJSON(needs.process-mappings.outputs) }}'
          
          # Convert the results into an array and save as JSON
          merged_json=$(echo "$results" | jq -c '[.[]]')
          echo "merged_results=$merged_json" >> $GITHUB_OUTPUT

      - name: Show Merged Results
        run: |
          echo "Merged Results:"
          echo '${{ steps.merge.outputs.merged_results }}' | jq '.'

      