name: Matrix Output Collection

on:
  push:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [apple, banana, cherry]

    outputs:
      images: ${{ steps.set-output.outputs.images }}

    steps:
      - name: Set Image Name
        id: image
        run: echo "name=${{ matrix.item }}" >> $GITHUB_OUTPUT

      - name: Generate Output
        id: set-output
        run: |
          IMAGE_INFO=$(jq -c -n --arg key "${{ matrix.item }}" --arg url "${{ matrix.item }}" '{ ($key): $url }')
          echo "images=$IMAGE_INFO" >> $GITHUB_OUTPUT

  collect-outputs:
    runs-on: ubuntu-latest
    needs: matrix-job
    outputs:
      merged_json: ${{ steps.merge.outputs.result }}
    steps:
      - name: Initialize JSON Object
        run: echo '{}' > merged.json

      - name: Merge Matrix Outputs
        id: merge
        run: |
          JSON_OBJ='{}'
          echo "${{ needs.matrix-job.outputs.images }}"
          for item in apple banana cherry; do
            PART='${{ needs.matrix-job.outputs.images }}'
            JSON_OBJ=$(echo $JSON_OBJ | jq --argjson part "$PART" '. + $part')
          done
          echo "$JSON_OBJ" > merged.json
          echo "result=$(cat merged.json)" >> $GITHUB_OUTPUT

      - name: Print Merged JSON
        run: cat merged.json

      