name: Matrix Output Collection

on:
  push:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: [apple, banana, cherry]

    steps:
      - name: Set Image Name
        id: image
        run: echo "name=${{ matrix.item }}" >> $GITHUB_OUTPUT

      - name: Generate Output
        id: set-output
        run: |
          IMAGE_INFO=$(jq -c -n --arg key "${{ matrix.item }}" --arg url "${{ matrix.item }}" '{ ($key): $url }')
          echo "$IMAGE_INFO" > output.json  # Save JSON to a file

      - name: Upload Matrix Outputs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: matrix-outputs
          path: output.json  # Upload the output file

  collect-outputs:
    runs-on: ubuntu-latest
    needs: matrix-job
    steps:
      - name: Download Matrix Outputs Artifact
        uses: actions/download-artifact@v3
        with:
          name: matrix-outputs  # Artifact name we uploaded earlier
          path: ./artifacts  # Directory to store the downloaded artifact

      - name: Merge Matrix Outputs
        id: merge
        run: |
          JSON_OBJ='{}'

          # Iterate through all output.json files in the artifact folder
          for file in ./artifacts/*; do
            PART=$(cat "$file")
            JSON_OBJ=$(echo $JSON_OBJ | jq --argjson part "$PART" '. + $part')
          done

          # Save the final merged JSON
          echo "$JSON_OBJ" > merged.json
          echo "result=$(cat merged.json)" >> $GITHUB_OUTPUT

      - name: Print Merged JSON
        run: cat merged.json

      